-- CREATING NEW USER TABLE INTO ADMIN DB FOR ADMIN CONTROLS

CREATE TABLE USER(
U_NAME VARCHAR(25) NOT NULL,
EMAIL VARCHAR(50),
PASS VARCHAR(30),
CONF_PASS VARCHAR(30), 
PRIMARY KEY(U_NAME));

-- ADDING NEW USERS TO USER TABLE BY ADMIN

INSERT INTO USER VALUES ('AJAY','AJAY@GMAIL.COM','SJC','SJC');
INSERT INTO USER VALUES ('JUDIN','JUDIN@GMAIL.COM','SJC','SJC');
INSERT INTO USER VALUES ('JUSTIN','JUSTIN@GMAIL.COM','SJC','SJX');
INSERT INTO USER VALUES ('NOYAL','NOYAL@GMAIL.COM','SJC','SJC');
INSERT INTO USER VALUES ('VISHNU','VISHNU@GMAIL.COM','SJC','SJC');

-- VERIFICATION OF PASSWORD

SELECT U_NAME,EMAIL,PASS FROM USER WHERE PASS = CONF_PASS;

-- UPDATING USER RECORDS AFTER ACCOUNT CREATION 

UPDATE USER SET U_NAME = 'CHOICE' WHERE U_NAME = 'NOYAL';
UPDATE USER SET EMAIL = 'ANONY@GMAIL.COM' WHERE U_NAME = 'VISHNU';
ALTER TABLE USER ADD COLUMN BIOGRAPHY VARCHAR(50);
UPDATE USER SET BIOGRAPHY = 'I AM A CODER' WHERE U_NAME = 'AJAY';

-- BELOW QUERY ONLY FOR VERIFICATION OF ABOVE QUERY SUCCESS
SELECT * FROM USER;

-- ADMIN DELETING USER FROM USER TABLE

DELETE FROM USER WHERE U_NAME = 'JUSTIN'  AND CONF_PASS!= 'SJC';